version: "2"
services:

  mongodb:
    image: mongo:4.0
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: example
    volumes:
      - /tmp/mongo/data:/data/db
      - ./docker/mongo/init/:/docker-entrypoint-initdb.d/